deploymentName: eurekaserver
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: atulpatel2001/eureka-server
  tag: latest

containerPort: 8073

service:
  type: ClusterIP
  port: 8073
  targetPort: 8073

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
datasource_url_enabled: false
datasource_password_enabled: false
datasource_username_enabled: false
rabbitmq_enabled: true
keyclaok_enabled: false
db_health: false
dbName: false
userName: false
password: false
microservice_health: true
realm_enable: false
secret_enable: false
clientId_enable: false


livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8073
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
readinessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8073
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6