deploymentName: gatewayserver
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: atulpatel2001/apigateway-sever
  tag: latest

containerPort: 8074

service:
  type: LoadBalancer
  port: 8074
  targetPort: 8074

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: false
kafka_enabled: false
datasource_url_enabled: false
datasource_password_enabled: false
datasource_username_enabled: false
rabbitmq_enabled: true
keyclaok_enabled: true
realm_enable: true
secret_enable: true
clientId_enable: true
db_health: false
dbName: false
userName: false
password: false
microservice_health: true



livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8074
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
readinessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8074
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6