deploymentName: address-service
serviceName: address-service
appLabel: address-service
appName: address-service

replicaCount: 1

image:
  repository: atulpatel2001/address-server
  tag: latest

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
datasource_url_enabled: true
datasource_password_enabled: true
datasource_username_enabled: true
rabbitmq_enabled: true