deploymentName: address
serviceName: address
appLabel: address
appName: address

replicaCount: 1

image:
  repository: atulpatel2001/address-server
  tag: latest

containerPort: 8081

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081


appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
datasource_url_enabled: true
datasource_password_enabled: true
datasource_username_enabled: true
rabbitmq_enabled: true
keyclaok_enabled: false
db_health: false
dbName: false
userName: false
password: false
microservice_health: true



database:
  host: addressservicedb
  port: 5433
  username: postgres
  password: root123
  dbName: addressservicedb




livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
readinessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6