deploymentName: configserver
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1

image:
  repository: atulpatel2001/config-server
  tag: latest

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
datasource_url_enabled: false
datasource_password_enabled: false
datasource_username_enabled: false
rabbitmq_enabled: true
keyclaok_enabled: false


livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8071
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
readinessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8071
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6