deploymentName: keycloakdb
serviceName: keycloakdb
appLabel: keycloakdb
appName: keycloakdb

replicaCount: 1

image:
  repository: postgres
  tag: latest

containerPort: 5432

service:
  type: ClusterIP
  port: 5431
  targetPort: 5432

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
datasource_url_enabled: false
datasource_password_enabled: false
datasource_username_enabled: false
rabbitmq_enabled: false
keyclaok_enabled: false
db_health: true
dbName: true
userName: true
password: true
microservice_health: false
realm_enable: false
secret_enable: false
clientId_enable: false

database:
  host: keycloakdb
  port: 5431
  username: postgres
  password: root123
  dbName: keycloakdb

livenessProbe:
  command: ["pg_isready"]
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
readinessProbe:
  command: ["pg_isready"]
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6