apiVersion: v1
kind: Service
metadata:
  name: addressservicedb
spec:
  selector:
    app: addressservicedb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressservicedb
  labels:
    app: addressservicedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressservicedb
  template:
    metadata:
      labels:
        app: addressservicedb
    spec:
      containers:
        - name: addressservicedb
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: addressservicedb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: root123
          readinessProbe:
            exec:
              command: ["pg_isready"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command: ["pg_isready"]
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
