apiVersion: v1
kind: Service
metadata:
  name: address-service
spec:
  selector:
    app: address-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-service
  labels:
    app: address-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-service
  template:
    metadata:
      labels:
        app: address-service
    spec:
      containers:
        - name: address-service
          image: atulpatel2001/address-server:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              value: address
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver:8071/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://addressservicedb:5432/addressservicedb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root123
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver:8073/eureka/
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
