apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: atulpatel2001/user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: user
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver:8071/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://userservicedb:5432/userservicedb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root123
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver:8073/eureka/
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: KEYCLOAK_URL
              value: "http://keycloak:8072"
            - name: KEYCLOAK_CLIENT_ID
              value: "food_swift"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "szzLAWSR0niKQYR7KD4b3rmBkVOOaSSl"

          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
