services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbit
    container_name: rabbit
    networks:
      - atulpatel2001
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  keycloakdb:
    image: postgres
    container_name: keycloakdb
    networks:
      - atulpatel2001
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123

  addressservicedb:
    image: postgres
    container_name: addressservicedb
    networks:
      - atulpatel2001
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRES_DB: addressservicedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123

  userservicedb:
    image: postgres
    container_name: userservicedb
    networks:
      - atulpatel2001
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRES_DB: userservicedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    ports:
      - "8072:8080"
    depends_on:
      keycloakdb:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    networks:
      - atulpatel2001


  configserver:
    image: atulpatel2001/config-server:latest
    container_name: configserver
    networks:
      - atulpatel2001
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/liveness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: rabbit


  eurekaserver:
    image: atulpatel2001/eureka-server:latest
    container_name: eurekaserver
    networks:
      - atulpatel2001
    ports:
      - "8073:8073"
    healthcheck:
      test: "curl --fail --silent localhost:8073/actuator/health/liveness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/





  address-service:
    image: atulpatel2001/address-server:latest
    container_name: address-service
    ports:
      - "8081:8081"
    networks:
      - atulpatel2001
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/liveness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      addressservicedb:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

    environment:
      SPRING_APPLICATION_NAME: address
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_URL: jdbc:postgresql://addressservicedb:5434/addressservicedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8073/eureka/

  user-service:
    image: atulpatel2001/user-service:latest
    container_name: user-service
    ports:
      - "8080:8081"
    networks:
      - atulpatel2001
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/liveness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      userservicedb:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

    environment:
      SPRING_APPLICATION_NAME: user
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_URL: jdbc:postgresql://userservicedb:5433/userservicedb

      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8073/eureka/


  gatewayserver:
    image: "atulpatel2001/apigateway-sever:latest"
    container_name: gateway-server
    ports:
      - "8074:8074"
    healthcheck:
      test: "curl --fail --silent localhost:8074/actuator/health/liveness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy

    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8073/eureka/







networks:
  atulpatel2001:
    driver: bridge