deploymentName: user
serviceName: user
appLabel: user
appName: user

replicaCount: 1

image:
  repository: atulpatel2001/user-service
  tag: latest

containerPort: 8080

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false
datasource_url_enabled: true
datasource_password_enabled: true
datasource_username_enabled: true
rabbitmq_enabled: true
keyclaok_enabled: true
db_health: false
dbName: false
userName: false
password: false
microservice_health: true

database:
  host: userservicedb
  port: 5432
  username: postgres
  password: root123
  dbName: userservicedb

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
readinessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6