package com.food.app.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.groups.Default;
import lombok.Data;


@Data
@Schema(name = "Area", description = "This Schema Holds Area Information")
public class AreaDto {
    public interface Create extends Default {}
    public interface Update extends Default {}


    @Schema(description = "Unique identifier for the Area", example = "1")
    @Null(groups = Create.class, message = "Id Not Require , Id is AutoGenerated")
    @NotNull(groups = Update.class, message = "ID is required for update")
    private Long id;

    @Schema(description = "Name of the Area", example = "Thaltej")
    @NotEmpty(groups = {Default.class, Create.class, Update.class}, message = "Area name can not be null or empty")
    @Pattern(regexp = "^[a-zA-Z]+$", groups = {Default.class, Create.class, Update.class}, message = "Only character values are allowed")
    private String name;

    @Schema(description = "City Id For Area", example = "1")
    @NotNull(groups = {Default.class, Create.class, Update.class}, message = "Area Id is Must Be Require!")
    private Long cityId;

    @Schema(description = "PinCode of Area", example = "383236")
    @Pattern(groups = {Default.class, Create.class, Update.class},regexp = "(^$|[0-9]{6})", message = "PinCode must be 6 digits without any special characters or alphabets")
    @NotEmpty(groups = {Default.class, Create.class, Update.class},message = "PinCode can not be null or empty")
    private String pinCode;



}
