package com.food.app.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;
import jakarta.validation.groups.Default;
import lombok.Data;


@Data
@Schema(name = "City", description = "This Schema Holds City Information")
public class CityDto {
    public interface Create extends Default {}
    public interface Update extends Default {}


    @Schema(description = "Unique identifier for the City", example = "1")
    @Null(groups = Create.class, message = "Id Not Require , Id is AutoGenerated")
    @NotNull(groups = Update.class, message = "ID is required for update")
    private Long id;



    @Schema(description = "Name of the city", example = "ahmedabad")
    @NotEmpty(groups = {Default.class, Create.class, Update.class}, message = "City name can not be null or empty")
    @Pattern(regexp = "^[a-zA-Z]+$", groups = {Default.class, Create.class, Update.class}, message = "Only character values are allowed")
    private String name;

    @Schema(description = "District Id For City", example = "1")
    @NotNull(groups = {Default.class, Create.class, Update.class}, message = "District Id is Must Be Require!")
    private Long districtId;
}
