package com.food.app.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.groups.Default;
import lombok.Data;

@Data
@Schema(name = "District", description = "This Schema Holds District Information")
public class DistrictDto {
    public interface Create extends Default {}
    public interface Update extends Default {}


    @Schema(description = "Unique identifier for the District", example = "1")
    @Null(groups = DistrictDto.Create.class, message = "Id Not Require , Id is AutoGenerated")
    @NotNull(groups = DistrictDto.Update.class, message = "ID is required for update")
    private Long id;

    @Schema(description = "Name of the District", example = "Mahesana")
    @NotEmpty(groups = {Default.class, DistrictDto.Create.class, DistrictDto.Update.class}, message = "District name can not be null or empty")
    @Pattern(regexp = "^[a-zA-Z]+$", groups = {Default.class, DistrictDto.Create.class, DistrictDto.Update.class}, message = "Only character values are allowed")
    private String name;

    @Schema(description = "State Id For District", example = "1")
    @NotNull(groups = {Default.class, DistrictDto.Create.class, DistrictDto.Update.class}, message = "State Id is Must Be Require!")
    private Long stateId;
    
}
